services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    image: juandelaf/net-tension-etl:latest
    container_name: nettension-etl
    volumes:
      - nettension-data:/app/data
    environment:
      - PYTHONPATH=/app/src

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    image: juandelaf/net-tension-dashboard:latest
    container_name: nettension-dashboard
    ports:
      - "8501:8501"
    volumes:
      - nettension-data:/app/data
    depends_on:
      etl:
        condition: service_completed_successfully

volumes:
  nettension-data:
