{
  "name": "NetTension Model",
  "culture": "en-US",
  "compatibilityLevel": 1603,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "dim_time",
        "description": "Calendar dimension: 83 quarters (2005T1-2025T4)",
        "columns": [
          { "name": "time_key", "dataType": "datetime", "isHidden": false },
          { "name": "trimestre_dt", "dataType": "datetime", "isHidden": false },
          { "name": "year", "dataType": "int64", "isHidden": false },
          { "name": "quarter", "dataType": "int64", "isHidden": false },
          { "name": "year_quarter", "dataType": "string", "isHidden": false }
        ],
        "partitions": [
          {
            "name": "dim_time",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Parquet.Document(File.Contents(\"data/processed/dim_time.parquet\")),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\nin\n    #\"Promoted Headers\""
            }
          }
        ],
        "annotations": [
          { "name": "Source_Type", "value": "ESTIMATED" },
          { "name": "Row_Count", "value": "83" }
        ]
      },
      {
        "name": "dim_operator",
        "description": "Operator dimension: 32 operators with group classification",
        "columns": [
          { "name": "operator_key", "dataType": "string", "isHidden": false },
          { "name": "operator_group", "dataType": "string", "isHidden": false },
          { "name": "is_incumbent", "dataType": "boolean", "isHidden": false }
        ],
        "partitions": [
          {
            "name": "dim_operator",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Parquet.Document(File.Contents(\"data/processed/dim_operator.parquet\")),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\nin\n    #\"Promoted Headers\""
            }
          }
        ],
        "annotations": [
          { "name": "Source_Type", "value": "ESTIMATED" },
          { "name": "Row_Count", "value": "32" }
        ]
      },
      {
        "name": "dim_service",
        "description": "Service/concept dimension: 38 combos with market type and category",
        "columns": [
          { "name": "service_key", "dataType": "string", "isHidden": false },
          { "name": "servicio", "dataType": "string", "isHidden": false },
          { "name": "concepto", "dataType": "string", "isHidden": false },
          { "name": "market_type", "dataType": "string", "isHidden": false },
          { "name": "category", "dataType": "string", "isHidden": false }
        ],
        "partitions": [
          {
            "name": "dim_service",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Parquet.Document(File.Contents(\"data/processed/dim_service.parquet\")),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\nin\n    #\"Promoted Headers\""
            }
          }
        ],
        "annotations": [
          { "name": "Source_Type", "value": "OBSERVED" },
          { "name": "Row_Count", "value": "38" }
        ]
      },
      {
        "name": "dim_geography",
        "description": "Geography dimension: Spain (ES) as case study",
        "columns": [
          { "name": "geography_key", "dataType": "string", "isHidden": false },
          { "name": "pais", "dataType": "string", "isHidden": false },
          { "name": "geo_code", "dataType": "string", "isHidden": false },
          { "name": "region", "dataType": "string", "isHidden": false }
        ],
        "partitions": [
          {
            "name": "dim_geography",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Parquet.Document(File.Contents(\"data/processed/dim_geography.parquet\")),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\nin\n    #\"Promoted Headers\""
            }
          }
        ],
        "annotations": [
          { "name": "Source_Type", "value": "CONSTANT" },
          { "name": "Row_Count", "value": "1" }
        ]
      },
      {
        "name": "dim_eu_context",
        "description": "European benchmarking context: ETNO, GSMA, Sandvine indicators",
        "columns": [
          { "name": "indicator", "dataType": "string", "isHidden": false },
          { "name": "value", "dataType": "double", "isHidden": false },
          { "name": "unit", "dataType": "string", "isHidden": false },
          { "name": "source", "dataType": "string", "isHidden": false }
        ],
        "partitions": [
          {
            "name": "dim_eu_context",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Parquet.Document(File.Contents(\"data/processed/dim_eu_context.parquet\")),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\nin\n    #\"Promoted Headers\""
            }
          }
        ],
        "annotations": [
          { "name": "Source_Type", "value": "OBSERVED" },
          { "name": "Row_Count", "value": "21" }
        ]
      },
      {
        "name": "fact_observed_agg",
        "description": "Aggregated quarterly metrics (fact table): traffic, revenue, lines, KPIs",
        "columns": [
          { "name": "trimestre_dt", "dataType": "datetime", "isHidden": false },
          { "name": "data_traffic", "dataType": "double", "isHidden": false, "description": "Total data traffic, GB" },
          { "name": "voice_traffic", "dataType": "double", "isHidden": false, "description": "Total voice traffic, minutes" },
          { "name": "revenue", "dataType": "double", "isHidden": false, "description": "Total revenue, EUR" },
          { "name": "total_lines", "dataType": "double", "isHidden": false, "description": "Active lines/accesos" },
          { "name": "data_traffic_index", "dataType": "double", "isHidden": false, "description": "Normalized (2005T1=100)" },
          { "name": "revenue_index", "dataType": "double", "isHidden": false, "description": "Normalized (2005T1=100)" },
          { "name": "nsi", "dataType": "double", "isHidden": false, "description": "Network Stress Index: traffic / lines" },
          { "name": "revenue_per_traffic", "dataType": "double", "isHidden": false },
          { "name": "revenue_per_line", "dataType": "double", "isHidden": false },
          { "name": "year", "dataType": "int64", "isHidden": false },
          { "name": "quarter", "dataType": "int64", "isHidden": false }
        ],
        "measures": [
          {
            "name": "Traffic CAGR",
            "description": "Compound Annual Growth Rate of data traffic",
            "expression": "VAR StartVal = CALCULATE(SUM(fact_observed_agg[data_traffic]), dim_time[year] = 2005, dim_time[quarter] = 1)\nVAR EndVal = CALCULATE(SUM(fact_observed_agg[data_traffic]), dim_time[year] = 2025, dim_time[quarter] = 4)\nVAR Periods = 20\nRETURN DIVIDE(EndVal, StartVal, 0) ^ (1 / Periods) - 1",
            "formatString": "0.00%"
          },
          {
            "name": "Revenue CAGR",
            "expression": "VAR StartVal = CALCULATE(SUM(fact_observed_agg[revenue]), dim_time[year] = 2005, dim_time[quarter] = 1)\nVAR EndVal = CALCULATE(SUM(fact_observed_agg[revenue]), dim_time[year] = 2025, dim_time[quarter] = 4)\nVAR Periods = 20\nRETURN DIVIDE(EndVal, StartVal, 0) ^ (1 / Periods) - 1",
            "formatString": "0.00%"
          },
          {
            "name": "CAGR Gap",
            "description": "Traffic CAGR minus Revenue CAGR (Scissors Effect)",
            "expression": "[Traffic CAGR] - [Revenue CAGR]",
            "formatString": "0.00%"
          },
          {
            "name": "Avg NSI",
            "description": "Average Network Stress Index",
            "expression": "AVERAGE(fact_observed_agg[nsi])",
            "formatString": "#,##0"
          },
          {
            "name": "Avg ARPU",
            "description": "Average Revenue Per Line",
            "expression": "AVERAGE(fact_observed_agg[revenue_per_line])",
            "formatString": "#,##0.00"
          }
        ],
        "partitions": [
          {
            "name": "fact_observed_agg",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Parquet.Document(File.Contents(\"data/processed/fact_observed_agg.parquet\")),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\nin\n    #\"Promoted Headers\""
            }
          }
        ],
        "annotations": [
          { "name": "Source_Type", "value": "ESTIMATED" },
          { "name": "Row_Count", "value": "83" }
        ]
      },
      {
        "name": "fact_eurostat_es",
        "description": "Spain macroeconomic data: population, GDP (Eurostat)",
        "columns": [
          { "name": "year", "dataType": "int64", "isHidden": false },
          { "name": "population", "dataType": "double", "isHidden": false },
          { "name": "gdp_meur", "dataType": "double", "isHidden": false },
          { "name": "gdp_per_capita", "dataType": "double", "isHidden": false }
        ],
        "measures": [
          {
            "name": "Telecom GDP Share",
            "description": "Telecom revenue as percentage of GDP",
            "expression": "VAR TelecomRev = SUM(fact_observed_agg[revenue])\nVAR GDP = SUM(fact_eurostat_es[gdp_meur]) * 1000000\nRETURN DIVIDE(TelecomRev, GDP, 0)",
            "formatString": "0.00%"
          }
        ],
        "partitions": [
          {
            "name": "fact_eurostat_es",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Parquet.Document(File.Contents(\"data/processed/fact_eurostat_es.parquet\")),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\nin\n    #\"Promoted Headers\""
            }
          }
        ],
        "annotations": [
          { "name": "Source_Type", "value": "OBSERVED" },
          { "name": "Row_Count", "value": "66" }
        ]
      },
      {
        "name": "kpi_hhi",
        "description": "Herfindahl-Hirschman Index per quarter with classification",
        "columns": [
          { "name": "trimestre", "dataType": "string", "isHidden": false },
          { "name": "hhi", "dataType": "double", "isHidden": false },
          { "name": "num_operators", "dataType": "int64", "isHidden": false },
          { "name": "trimestre_dt", "dataType": "datetime", "isHidden": false },
          { "name": "year", "dataType": "int64", "isHidden": false },
          { "name": "classification", "dataType": "string", "isHidden": false }
        ],
        "measures": [
          {
            "name": "HHI Avg",
            "description": "Average HHI over selected period",
            "expression": "AVERAGE(kpi_hhi[hhi])",
            "formatString": "#,##0"
          },
          {
            "name": "HHI Classification",
            "expression": "MIN(kpi_hhi[classification])",
            "formatString": ""
          }
        ],
        "partitions": [
          {
            "name": "kpi_hhi",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Parquet.Document(File.Contents(\"data/processed/kpi_hhi.parquet\")),\n    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars = true])\nin\n    #\"Promoted Headers\""
            }
          }
        ],
        "annotations": [
          { "name": "Source_Type", "value": "ESTIMATED" },
          { "name": "Row_Count", "value": "83" }
        ]
      }
    ],
    "relationships": [
      {
        "name": "r_fact_time",
        "fromTable": "fact_observed_agg",
        "fromColumn": "trimestre_dt",
        "toTable": "dim_time",
        "toColumn": "trimestre_dt",
        "isActive": true,
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "r_hhi_time",
        "fromTable": "kpi_hhi",
        "fromColumn": "trimestre_dt",
        "toTable": "dim_time",
        "toColumn": "trimestre_dt",
        "isActive": true,
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "r_euro_year",
        "fromTable": "fact_eurostat_es",
        "fromColumn": "year",
        "toTable": "dim_time",
        "toColumn": "year",
        "isActive": true,
        "crossFilteringBehavior": "singleDirection"
      }
    ]
  }
}
